[package]
name = "doomgeneric_xlib"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"

[[bin]]
name = "doomgeneric_xlib"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
libc = "0.2"
doomgeneric_fs = { path = "../fs" }
rust_doomgeneric = { path = "../engine" }
doomgeneric_cmdline = { path = "../cmdline" }
