use crate::d_player::AmmoType;
use crate::p_mobj::StateNum;
#[derive(Copy, Clone)]
pub struct WeaponInfo {
    pub ammo: AmmoType,
    pub upstate: StateNum,
    pub downstate: StateNum,
    pub readystate: StateNum,
    pub atkstate: StateNum,
    pub flashstate: StateNum,
}
pub static WEAPONINFO: [WeaponInfo; 9] = [
    WeaponInfo {
        ammo: AmmoType::Noammo,
        upstate: StateNum::Punchup,
        downstate: StateNum::Punchdown,
        readystate: StateNum::Punch,
        atkstate: StateNum::Punch1,
        flashstate: StateNum::Null,
    },
    WeaponInfo {
        ammo: AmmoType::Clip,
        upstate: StateNum::Pistolup,
        downstate: StateNum::Pistoldown,
        readystate: StateNum::Pistol,
        atkstate: StateNum::Pistol1,
        flashstate: StateNum::Pistolflash,
    },
    WeaponInfo {
        ammo: AmmoType::Shell,
        upstate: StateNum::Sgunup,
        downstate: StateNum::Sgundown,
        readystate: StateNum::Sgun,
        atkstate: StateNum::Sgun1,
        flashstate: StateNum::Sgunflash1,
    },
    WeaponInfo {
        ammo: AmmoType::Clip,
        upstate: StateNum::Chainup,
        downstate: StateNum::Chaindown,
        readystate: StateNum::Chain,
        atkstate: StateNum::Chain1,
        flashstate: StateNum::Chainflash1,
    },
    WeaponInfo {
        ammo: AmmoType::Misl,
        upstate: StateNum::Missileup,
        downstate: StateNum::Missiledown,
        readystate: StateNum::Missile,
        atkstate: StateNum::Missile1,
        flashstate: StateNum::Missileflash1,
    },
    WeaponInfo {
        ammo: AmmoType::Cell,
        upstate: StateNum::Plasmaup,
        downstate: StateNum::Plasmadown,
        readystate: StateNum::Plasma,
        atkstate: StateNum::Plasma1,
        flashstate: StateNum::Plasmaflash1,
    },
    WeaponInfo {
        ammo: AmmoType::Cell,
        upstate: StateNum::Bfgup,
        downstate: StateNum::Bfgdown,
        readystate: StateNum::Bfg,
        atkstate: StateNum::Bfg1,
        flashstate: StateNum::Bfgflash1,
    },
    WeaponInfo {
        ammo: AmmoType::Noammo,
        upstate: StateNum::Sawup,
        downstate: StateNum::Sawdown,
        readystate: StateNum::Saw,
        atkstate: StateNum::Saw1,
        flashstate: StateNum::Null,
    },
    WeaponInfo {
        ammo: AmmoType::Shell,
        upstate: StateNum::Dsgunup,
        downstate: StateNum::Dsgundown,
        readystate: StateNum::Dsgun,
        atkstate: StateNum::Dsgun1,
        flashstate: StateNum::Dsgunflash1,
    },
];
