use crate::fixed_cstr::FixedCStr;
use crate::w_wad::LumpNum;
#[derive(Copy, Clone, PartialEq, Eq)]
#[allow(dead_code)] // mirrors a C index table; variant order must stay
pub enum MusicName {
    MusNone,
    E1m1,
    E1m2,
    E1m3,
    E1m4,
    E1m5,
    E1m6,
    E1m7,
    E1m8,
    E1m9,
    E2m1,
    E2m2,
    E2m3,
    E2m4,
    E2m5,
    E2m6,
    E2m7,
    E2m8,
    E2m9,
    E3m1,
    E3m2,
    E3m3,
    E3m4,
    E3m5,
    E3m6,
    E3m7,
    E3m8,
    E3m9,
    Inter,
    Intro,
    Bunny,
    Victor,
    Introa,
    Runnin,
    Stalks,
    Countd,
    Betwee,
    Doom,
    TheDa,
    Shawn,
    Ddtblu,
    InCit,
    Dead,
    Stlks2,
    Theda2,
    Doom2,
    Ddtbl2,
    Runni2,
    Dead2,
    Stlks3,
    Romero,
    Shawn2,
    Messag,
    Count2,
    Ddtbl3,
    Ampie,
    Theda3,
    Adrian,
    Messg2,
    Romer2,
    Tense,
    Shawn3,
    Openin,
    Evil,
    Ultima,
    ReadM,
    Dm2ttl,
    Dm2int,
}
pub const NUMMUSIC: i32 = 68;
#[derive(Copy, Clone)]
pub struct SfxInfo {
    pub tagname: Option<&'static str>,
    pub name: FixedCStr<9>,
    pub priority: i32,
    pub link: Option<SfxId>,
    pub pitch: i32,
    pub volume: i32,
    pub usefulness: i32,
    pub lumpnum: Option<LumpNum>,
    pub numchannels: i32,
}
#[derive(Copy, Clone)]
pub struct MusicInfo {
    pub name: FixedCStr<7>,
    pub lumpnum: Option<LumpNum>,
    pub handle: usize,
}
#[derive(Copy, Clone, PartialEq, Eq)]
#[allow(dead_code)] // mirrors a C index table; variant order must stay
pub enum SfxName {
    SfxNone,
    Pistol,
    Shotgn,
    Sgcock,
    Dshtgn,
    Dbopn,
    Dbcls,
    Dbload,
    Plasma,
    Bfg,
    Sawup,
    Sawidl,
    Sawful,
    Sawhit,
    Rlaunc,
    Rxplod,
    Firsht,
    Firxpl,
    Pstart,
    Pstop,
    Doropn,
    Dorcls,
    Stnmov,
    Swtchn,
    Swtchx,
    Plpain,
    Dmpain,
    Popain,
    Vipain,
    Mnpain,
    Pepain,
    Slop,
    Itemup,
    Wpnup,
    Oof,
    Telept,
    Posit1,
    Posit2,
    Posit3,
    Bgsit1,
    Bgsit2,
    Sgtsit,
    Cacsit,
    Brssit,
    Cybsit,
    Spisit,
    Bspsit,
    Kntsit,
    Vilsit,
    Mansit,
    Pesit,
    Sklatk,
    Sgtatk,
    Skepch,
    Vilatk,
    Claw,
    Skeswg,
    Pldeth,
    Pdiehi,
    Podth1,
    Podth2,
    Podth3,
    Bgdth1,
    Bgdth2,
    Sgtdth,
    Cacdth,
    Skldth,
    Brsdth,
    Cybdth,
    Spidth,
    Bspdth,
    Vildth,
    Kntdth,
    Pedth,
    Skedth,
    Posact,
    Bgact,
    Dmact,
    Bspact,
    Bspwlk,
    Vilact,
    Noway,
    Barexp,
    Punch,
    Hoof,
    Metal,
    Chgun,
    Tink,
    Bdopn,
    Bdcls,
    Itmbk,
    Flame,
    Flamst,
    Getpow,
    Bospit,
    Boscub,
    Bossit,
    Bospn,
    Bosdth,
    Manatk,
    Mandth,
    Sssit,
    Ssdth,
    Keenpn,
    Keendt,
    Skeact,
    Skesit,
    Skeatk,
    Radio,
}
pub const NUMSFX: usize = 109;
const INITIAL_S_MUSIC: [MusicInfo; 68] = [
    MusicInfo {
        name: FixedCStr([0u8; 7]),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e1m1\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e1m2\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e1m3\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e1m4\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e1m5\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e1m6\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e1m7\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e1m8\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e1m9\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e2m1\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e2m2\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e2m3\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e2m4\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e2m5\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e2m6\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e2m7\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e2m8\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e2m9\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e3m1\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e3m2\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e3m3\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e3m4\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e3m5\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e3m6\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e3m7\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e3m8\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"e3m9\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"inter\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"intro\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"bunny\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"victor\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"introa\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"runnin\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"stalks\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"countd\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"betwee\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"doom\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"the_da\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"shawn\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"ddtblu\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"in_cit\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"dead\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"stlks2\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"theda2\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"doom2\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"ddtbl2\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"runni2\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"dead2\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"stlks3\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"romero\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"shawn2\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"messag\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"count2\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"ddtbl3\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"ampie\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"theda3\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"adrian\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"messg2\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"romer2\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"tense\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"shawn3\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"openin\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"evil\x00\x00\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"ultima\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"read_m\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"dm2ttl\x00"),
        lumpnum: None,
        handle: 0,
    },
    MusicInfo {
        name: FixedCStr(*b"dm2int\x00"),
        lumpnum: None,
        handle: 0,
    },
];

#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub struct SfxId(pub u32);

pub struct SoundsState {
    pub s_music: [MusicInfo; 68],
    pub s_sfx: [SfxInfo; 109],
}

impl Default for SoundsState {
    fn default() -> Self {
        Self::new()
    }
}

impl SoundsState {
    pub fn sfx_mut(&mut self, id: SfxId) -> &mut SfxInfo {
        &mut self.s_sfx[id.0 as usize]
    }

    // Kept out of line: `GameState::new` inlines every state constructor, and once
    // `init_game_state` passes 256 KB the Xtensa linker fails ("dangerous relocation:
    // l32r: literal target out of range") building the firmware. These are the biggest.
    #[inline(never)]
    pub fn new() -> Self {
        Self {
            s_music: INITIAL_S_MUSIC,
            s_sfx: [
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"none\0\0\0\0\0"),
                    priority: 0,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"pistol\0\0\0"),
                    priority: 64,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"shotgn\0\0\0"),
                    priority: 64,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"sgcock\0\0\0"),
                    priority: 64,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"dshtgn\0\0\0"),
                    priority: 64,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"dbopn\0\0\0\0"),
                    priority: 64,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"dbcls\0\0\0\0"),
                    priority: 64,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"dbload\0\0\0"),
                    priority: 64,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"plasma\0\0\0"),
                    priority: 64,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"bfg\0\0\0\0\0\0"),
                    priority: 64,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"sawup\0\0\0\0"),
                    priority: 64,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"sawidl\0\0\0"),
                    priority: 118,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"sawful\0\0\0"),
                    priority: 64,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"sawhit\0\0\0"),
                    priority: 64,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"rlaunc\0\0\0"),
                    priority: 64,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"rxplod\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"firsht\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"firxpl\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"pstart\0\0\0"),
                    priority: 100,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"pstop\0\0\0\0"),
                    priority: 100,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"doropn\0\0\0"),
                    priority: 100,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"dorcls\0\0\0"),
                    priority: 100,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"stnmov\0\0\0"),
                    priority: 119,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"swtchn\0\0\0"),
                    priority: 78,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"swtchx\0\0\0"),
                    priority: 78,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"plpain\0\0\0"),
                    priority: 96,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"dmpain\0\0\0"),
                    priority: 96,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"popain\0\0\0"),
                    priority: 96,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"vipain\0\0\0"),
                    priority: 96,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"mnpain\0\0\0"),
                    priority: 96,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"pepain\0\0\0"),
                    priority: 96,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"slop\0\0\0\0\0"),
                    priority: 78,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"itemup\0\0\0"),
                    priority: 78,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"wpnup\0\0\0\0"),
                    priority: 78,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"oof\0\0\0\0\0\0"),
                    priority: 96,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"telept\0\0\0"),
                    priority: 32,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"posit1\0\0\0"),
                    priority: 98,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"posit2\0\0\0"),
                    priority: 98,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"posit3\0\0\0"),
                    priority: 98,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"bgsit1\0\0\0"),
                    priority: 98,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"bgsit2\0\0\0"),
                    priority: 98,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"sgtsit\0\0\0"),
                    priority: 98,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"cacsit\0\0\0"),
                    priority: 98,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"brssit\0\0\0"),
                    priority: 94,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"cybsit\0\0\0"),
                    priority: 92,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"spisit\0\0\0"),
                    priority: 90,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"bspsit\0\0\0"),
                    priority: 90,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"kntsit\0\0\0"),
                    priority: 90,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"vilsit\0\0\0"),
                    priority: 90,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"mansit\0\0\0"),
                    priority: 90,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"pesit\0\0\0\0"),
                    priority: 90,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"sklatk\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"sgtatk\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"skepch\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"vilatk\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"claw\0\0\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"skeswg\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"pldeth\0\0\0"),
                    priority: 32,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"pdiehi\0\0\0"),
                    priority: 32,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"podth1\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"podth2\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"podth3\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"bgdth1\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"bgdth2\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"sgtdth\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"cacdth\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"skldth\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"brsdth\0\0\0"),
                    priority: 32,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"cybdth\0\0\0"),
                    priority: 32,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"spidth\0\0\0"),
                    priority: 32,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"bspdth\0\0\0"),
                    priority: 32,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"vildth\0\0\0"),
                    priority: 32,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"kntdth\0\0\0"),
                    priority: 32,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"pedth\0\0\0\0"),
                    priority: 32,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"skedth\0\0\0"),
                    priority: 32,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"posact\0\0\0"),
                    priority: 120,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"bgact\0\0\0\0"),
                    priority: 120,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"dmact\0\0\0\0"),
                    priority: 120,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"bspact\0\0\0"),
                    priority: 100,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"bspwlk\0\0\0"),
                    priority: 100,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"vilact\0\0\0"),
                    priority: 100,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"noway\0\0\0\0"),
                    priority: 78,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"barexp\0\0\0"),
                    priority: 60,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"punch\0\0\0\0"),
                    priority: 64,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"hoof\0\0\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"metal\0\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"chgun\0\0\0\0"),
                    priority: 64,
                    link: None,
                    pitch: 150,
                    volume: 0,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"tink\0\0\0\0\0"),
                    priority: 60,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"bdopn\0\0\0\0"),
                    priority: 100,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"bdcls\0\0\0\0"),
                    priority: 100,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"itmbk\0\0\0\0"),
                    priority: 100,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"flame\0\0\0\0"),
                    priority: 32,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"flamst\0\0\0"),
                    priority: 32,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"getpow\0\0\0"),
                    priority: 60,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"bospit\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"boscub\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"bossit\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"bospn\0\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"bosdth\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"manatk\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"mandth\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"sssit\0\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"ssdth\0\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"keenpn\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"keendt\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"skeact\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"skesit\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"skeatk\0\0\0"),
                    priority: 70,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
                SfxInfo {
                    tagname: None,
                    name: FixedCStr(*b"radio\0\0\0\0"),
                    priority: 60,
                    link: None,
                    pitch: -1,
                    volume: -1,
                    usefulness: 0,
                    lumpnum: None,
                    numchannels: -1,
                },
            ],
        }
    }

    // Must run only after `self` is at its final, permanently-stable address
    // (i.e. once already moved into GameState's 'static storage via
    // `Box::leak`) -- link's target address is computed from `self`'s own
    // location, which would be invalidated by any subsequent move. See
    // init_game_state().
    pub fn fixup_self_links(&mut self) {
        self.s_sfx[SfxName::Chgun as usize].link = Some(SfxId(SfxName::Pistol as u32));
    }
}
