use crate::fixed_cstr::FixedCStr;
#[derive(Copy, Clone, PartialEq, Eq)]
#[allow(dead_code)] // mirrors a C index table; discriminants must stay
pub enum MusicName {
    mus_None = 0,
    mus_e1m1 = 1,
    mus_e1m2 = 2,
    mus_e1m3 = 3,
    mus_e1m4 = 4,
    mus_e1m5 = 5,
    mus_e1m6 = 6,
    mus_e1m7 = 7,
    mus_e1m8 = 8,
    mus_e1m9 = 9,
    mus_e2m1 = 10,
    mus_e2m2 = 11,
    mus_e2m3 = 12,
    mus_e2m4 = 13,
    mus_e2m5 = 14,
    mus_e2m6 = 15,
    mus_e2m7 = 16,
    mus_e2m8 = 17,
    mus_e2m9 = 18,
    mus_e3m1 = 19,
    mus_e3m2 = 20,
    mus_e3m3 = 21,
    mus_e3m4 = 22,
    mus_e3m5 = 23,
    mus_e3m6 = 24,
    mus_e3m7 = 25,
    mus_e3m8 = 26,
    mus_e3m9 = 27,
    mus_inter = 28,
    mus_intro = 29,
    mus_bunny = 30,
    mus_victor = 31,
    mus_introa = 32,
    mus_runnin = 33,
    mus_stalks = 34,
    mus_countd = 35,
    mus_betwee = 36,
    mus_doom = 37,
    mus_the_da = 38,
    mus_shawn = 39,
    mus_ddtblu = 40,
    mus_in_cit = 41,
    mus_dead = 42,
    mus_stlks2 = 43,
    mus_theda2 = 44,
    mus_doom2 = 45,
    mus_ddtbl2 = 46,
    mus_runni2 = 47,
    mus_dead2 = 48,
    mus_stlks3 = 49,
    mus_romero = 50,
    mus_shawn2 = 51,
    mus_messag = 52,
    mus_count2 = 53,
    mus_ddtbl3 = 54,
    mus_ampie = 55,
    mus_theda3 = 56,
    mus_adrian = 57,
    mus_messg2 = 58,
    mus_romer2 = 59,
    mus_tense = 60,
    mus_shawn3 = 61,
    mus_openin = 62,
    mus_evil = 63,
    mus_ultima = 64,
    mus_read_m = 65,
    mus_dm2ttl = 66,
    mus_dm2int = 67,
}
pub const NUMMUSIC: i32 = 68;
#[derive(Copy, Clone)]
pub struct sfxinfo_struct {
    pub tagname: Option<&'static str>,
    pub name: FixedCStr<9>,
    pub priority: i32,
    pub link: Option<SfxId>,
    pub pitch: i32,
    pub volume: i32,
    pub usefulness: i32,
    pub lumpnum: i32,
    pub numchannels: i32,
}
pub type sfxinfo_t = sfxinfo_struct;
#[derive(Copy, Clone)]
pub struct musicinfo_t {
    pub name: FixedCStr<7>,
    pub lumpnum: i32,
    pub handle: usize,
}
#[derive(Copy, Clone, PartialEq, Eq)]
#[allow(dead_code)] // mirrors a C index table; discriminants must stay
pub enum SfxName {
    sfx_None = 0,
    sfx_pistol = 1,
    sfx_shotgn = 2,
    sfx_sgcock = 3,
    sfx_dshtgn = 4,
    sfx_dbopn = 5,
    sfx_dbcls = 6,
    sfx_dbload = 7,
    sfx_plasma = 8,
    sfx_bfg = 9,
    sfx_sawup = 10,
    sfx_sawidl = 11,
    sfx_sawful = 12,
    sfx_sawhit = 13,
    sfx_rlaunc = 14,
    sfx_rxplod = 15,
    sfx_firsht = 16,
    sfx_firxpl = 17,
    sfx_pstart = 18,
    sfx_pstop = 19,
    sfx_doropn = 20,
    sfx_dorcls = 21,
    sfx_stnmov = 22,
    sfx_swtchn = 23,
    sfx_swtchx = 24,
    sfx_plpain = 25,
    sfx_dmpain = 26,
    sfx_popain = 27,
    sfx_vipain = 28,
    sfx_mnpain = 29,
    sfx_pepain = 30,
    sfx_slop = 31,
    sfx_itemup = 32,
    sfx_wpnup = 33,
    sfx_oof = 34,
    sfx_telept = 35,
    sfx_posit1 = 36,
    sfx_posit2 = 37,
    sfx_posit3 = 38,
    sfx_bgsit1 = 39,
    sfx_bgsit2 = 40,
    sfx_sgtsit = 41,
    sfx_cacsit = 42,
    sfx_brssit = 43,
    sfx_cybsit = 44,
    sfx_spisit = 45,
    sfx_bspsit = 46,
    sfx_kntsit = 47,
    sfx_vilsit = 48,
    sfx_mansit = 49,
    sfx_pesit = 50,
    sfx_sklatk = 51,
    sfx_sgtatk = 52,
    sfx_skepch = 53,
    sfx_vilatk = 54,
    sfx_claw = 55,
    sfx_skeswg = 56,
    sfx_pldeth = 57,
    sfx_pdiehi = 58,
    sfx_podth1 = 59,
    sfx_podth2 = 60,
    sfx_podth3 = 61,
    sfx_bgdth1 = 62,
    sfx_bgdth2 = 63,
    sfx_sgtdth = 64,
    sfx_cacdth = 65,
    sfx_skldth = 66,
    sfx_brsdth = 67,
    sfx_cybdth = 68,
    sfx_spidth = 69,
    sfx_bspdth = 70,
    sfx_vildth = 71,
    sfx_kntdth = 72,
    sfx_pedth = 73,
    sfx_skedth = 74,
    sfx_posact = 75,
    sfx_bgact = 76,
    sfx_dmact = 77,
    sfx_bspact = 78,
    sfx_bspwlk = 79,
    sfx_vilact = 80,
    sfx_noway = 81,
    sfx_barexp = 82,
    sfx_punch = 83,
    sfx_hoof = 84,
    sfx_metal = 85,
    sfx_chgun = 86,
    sfx_tink = 87,
    sfx_bdopn = 88,
    sfx_bdcls = 89,
    sfx_itmbk = 90,
    sfx_flame = 91,
    sfx_flamst = 92,
    sfx_getpow = 93,
    sfx_bospit = 94,
    sfx_boscub = 95,
    sfx_bossit = 96,
    sfx_bospn = 97,
    sfx_bosdth = 98,
    sfx_manatk = 99,
    sfx_mandth = 100,
    sfx_sssit = 101,
    sfx_ssdth = 102,
    sfx_keenpn = 103,
    sfx_keendt = 104,
    sfx_skeact = 105,
    sfx_skesit = 106,
    sfx_skeatk = 107,
    sfx_radio = 108,
}
pub const NUMSFX: i32 = 109;
const INITIAL_S_MUSIC: [musicinfo_t; 68] = [
    musicinfo_t {
        name: FixedCStr([0u8; 7]),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e1m1\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e1m2\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e1m3\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e1m4\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e1m5\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e1m6\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e1m7\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e1m8\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e1m9\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e2m1\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e2m2\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e2m3\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e2m4\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e2m5\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e2m6\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e2m7\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e2m8\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e2m9\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e3m1\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e3m2\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e3m3\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e3m4\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e3m5\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e3m6\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e3m7\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e3m8\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"e3m9\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"inter\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"intro\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"bunny\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"victor\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"introa\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"runnin\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"stalks\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"countd\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"betwee\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"doom\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"the_da\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"shawn\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"ddtblu\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"in_cit\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"dead\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"stlks2\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"theda2\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"doom2\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"ddtbl2\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"runni2\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"dead2\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"stlks3\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"romero\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"shawn2\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"messag\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"count2\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"ddtbl3\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"ampie\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"theda3\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"adrian\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"messg2\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"romer2\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"tense\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"shawn3\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"openin\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"evil\x00\x00\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"ultima\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"read_m\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"dm2ttl\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
    musicinfo_t {
        name: FixedCStr(*b"dm2int\x00"),
        lumpnum: 0_i32,
        handle: 0,
    },
];

#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub struct SfxId(pub u32);

pub struct SoundsState {
    pub S_music: [musicinfo_t; 68],
    pub S_sfx: [sfxinfo_t; 109],
}

impl Default for SoundsState {
    fn default() -> Self {
        Self::new()
    }
}

impl SoundsState {
    pub fn sfx_mut(&mut self, id: SfxId) -> &mut sfxinfo_t {
        &mut self.S_sfx[id.0 as usize]
    }

    pub fn new() -> Self {
        SoundsState {
            S_music: INITIAL_S_MUSIC,
            S_sfx: [
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"none\0\0\0\0\0"),
                    priority: 0_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"pistol\0\0\0"),
                    priority: 64_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"shotgn\0\0\0"),
                    priority: 64_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"sgcock\0\0\0"),
                    priority: 64_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"dshtgn\0\0\0"),
                    priority: 64_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"dbopn\0\0\0\0"),
                    priority: 64_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"dbcls\0\0\0\0"),
                    priority: 64_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"dbload\0\0\0"),
                    priority: 64_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"plasma\0\0\0"),
                    priority: 64_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"bfg\0\0\0\0\0\0"),
                    priority: 64_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"sawup\0\0\0\0"),
                    priority: 64_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"sawidl\0\0\0"),
                    priority: 118_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"sawful\0\0\0"),
                    priority: 64_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"sawhit\0\0\0"),
                    priority: 64_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"rlaunc\0\0\0"),
                    priority: 64_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"rxplod\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"firsht\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"firxpl\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"pstart\0\0\0"),
                    priority: 100_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"pstop\0\0\0\0"),
                    priority: 100_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"doropn\0\0\0"),
                    priority: 100_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"dorcls\0\0\0"),
                    priority: 100_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"stnmov\0\0\0"),
                    priority: 119_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"swtchn\0\0\0"),
                    priority: 78_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"swtchx\0\0\0"),
                    priority: 78_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"plpain\0\0\0"),
                    priority: 96_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"dmpain\0\0\0"),
                    priority: 96_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"popain\0\0\0"),
                    priority: 96_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"vipain\0\0\0"),
                    priority: 96_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"mnpain\0\0\0"),
                    priority: 96_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"pepain\0\0\0"),
                    priority: 96_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"slop\0\0\0\0\0"),
                    priority: 78_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"itemup\0\0\0"),
                    priority: 78_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"wpnup\0\0\0\0"),
                    priority: 78_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"oof\0\0\0\0\0\0"),
                    priority: 96_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"telept\0\0\0"),
                    priority: 32_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"posit1\0\0\0"),
                    priority: 98_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"posit2\0\0\0"),
                    priority: 98_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"posit3\0\0\0"),
                    priority: 98_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"bgsit1\0\0\0"),
                    priority: 98_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"bgsit2\0\0\0"),
                    priority: 98_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"sgtsit\0\0\0"),
                    priority: 98_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"cacsit\0\0\0"),
                    priority: 98_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"brssit\0\0\0"),
                    priority: 94_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"cybsit\0\0\0"),
                    priority: 92_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"spisit\0\0\0"),
                    priority: 90_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"bspsit\0\0\0"),
                    priority: 90_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"kntsit\0\0\0"),
                    priority: 90_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"vilsit\0\0\0"),
                    priority: 90_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"mansit\0\0\0"),
                    priority: 90_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"pesit\0\0\0\0"),
                    priority: 90_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"sklatk\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"sgtatk\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"skepch\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"vilatk\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"claw\0\0\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"skeswg\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"pldeth\0\0\0"),
                    priority: 32_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"pdiehi\0\0\0"),
                    priority: 32_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"podth1\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"podth2\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"podth3\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"bgdth1\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"bgdth2\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"sgtdth\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"cacdth\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"skldth\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"brsdth\0\0\0"),
                    priority: 32_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"cybdth\0\0\0"),
                    priority: 32_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"spidth\0\0\0"),
                    priority: 32_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"bspdth\0\0\0"),
                    priority: 32_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"vildth\0\0\0"),
                    priority: 32_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"kntdth\0\0\0"),
                    priority: 32_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"pedth\0\0\0\0"),
                    priority: 32_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"skedth\0\0\0"),
                    priority: 32_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"posact\0\0\0"),
                    priority: 120_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"bgact\0\0\0\0"),
                    priority: 120_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"dmact\0\0\0\0"),
                    priority: 120_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"bspact\0\0\0"),
                    priority: 100_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"bspwlk\0\0\0"),
                    priority: 100_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"vilact\0\0\0"),
                    priority: 100_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"noway\0\0\0\0"),
                    priority: 78_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"barexp\0\0\0"),
                    priority: 60_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"punch\0\0\0\0"),
                    priority: 64_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"hoof\0\0\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"metal\0\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"chgun\0\0\0\0"),
                    priority: 64_i32,
                    link: None,
                    pitch: 150_i32,
                    volume: 0_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"tink\0\0\0\0\0"),
                    priority: 60_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"bdopn\0\0\0\0"),
                    priority: 100_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"bdcls\0\0\0\0"),
                    priority: 100_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"itmbk\0\0\0\0"),
                    priority: 100_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"flame\0\0\0\0"),
                    priority: 32_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"flamst\0\0\0"),
                    priority: 32_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"getpow\0\0\0"),
                    priority: 60_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"bospit\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"boscub\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"bossit\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"bospn\0\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"bosdth\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"manatk\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"mandth\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"sssit\0\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"ssdth\0\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"keenpn\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"keendt\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"skeact\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"skesit\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"skeatk\0\0\0"),
                    priority: 70_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
                sfxinfo_struct {
                    tagname: None,
                    name: FixedCStr(*b"radio\0\0\0\0"),
                    priority: 60_i32,
                    link: None,
                    pitch: -1_i32,
                    volume: -1_i32,
                    usefulness: 0_i32,
                    lumpnum: 0_i32,
                    numchannels: -1_i32,
                },
            ],
        }
    }

    // Must run only after `self` is at its final, permanently-stable address
    // (i.e. once already moved into GameState's 'static storage via
    // `Box::leak`) -- link's target address is computed from `self`'s own
    // location, which would be invalidated by any subsequent move. See
    // init_game_state().
    pub fn fixup_self_links(&mut self) {
        self.S_sfx[SfxName::sfx_chgun as usize].link = Some(SfxId(SfxName::sfx_pistol as u32));
    }
}
